/*
 * This file is generated by jOOQ.
 */
package com.example.jooq;


import com.example.jooq.tables.Customer;
import com.example.jooq.tables.Lot;


/**
 * Convenience access to all tables in purchase.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>purchase.customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>purchase.lot</code>.
     */
    public static final Lot LOT = Lot.LOT;
}
